### ISSUE TITLE
Reproducing the results on NTU & Penn Action datasets

### ISSUE THREAD

**Issue by dtoertei** [dluvizon/deephar#12]
Hi Diogo,

I would like to  run the evaluation scripts on action recognition benchmarks, however it seems that I cannot find the weights files needed:
-  deephar/releases/download/v0.3/weights_AR_merge_ep074_26-10-17.h5 
- deephar/releases/download/v0.4/weights_AR_merge_NTU_v2.h5
Did you upload them maybe to a different repository?

Kind regards,
Daniel

**Comment by dtoertei** [comment]
These links are working just good.

**Comment by dandingol03** [comment]
can you run eval_penn_ar_pe_merge successfully? i met an error as below:
``
Traceback (most recent call last):
  File "exp/pennaction/eval_penn_ar_pe_merge.py", line 62, in <module>
    model.load_weights(weights_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 2211, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 708, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/backend.py", line 3576, in batch_set_value
    x.assign(np.asarray(value, dtype=dtype(x)))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 858, in assign
    self._shape.assert_is_compatible_with(value_tensor.shape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_shape.py", line 1134, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (32,) and (3, 3, 32, 32) are incompatible
``
