### ISSUE TITLE
TypeError: 

### ISSUE THREAD

**Issue by wltnkim** [dluvizon/deephar#15]
I run

python3 exp/mpii/train_mpii_singleperson.py

but, 

==================================================================================================
Total params: 14,847,936
Trainable params: 14,669,952
Non-trainable params: 177,984
__________________________________________________________________________________________________
Traceback (most recent call last):
  File "exp/mpii/train_mpii_singleperson.py", line 97, in <module>
    initial_epoch=0)
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 2141, in fit_generator
    callbacks.on_epoch_begin(epoch)
  File "/usr/local/lib/python3.5/dist-packages/keras/callbacks.py", line 62, in on_epoch_begin
    callback.on_epoch_begin(epoch, logs)
  File "/usr/local/lib/python3.5/dist-packages/keras/callbacks.py", line 577, in on_epoch_begin
    lr = self.schedule(epoch)
TypeError: lr_scheduler() missing 1 required positional argument: 'lr'

How to fix it?

**Comment by dluvizon** [comment]
Please could you check your Keras version? It seems to be an API issue.

**Comment by wltnkim** [comment]
Keras version is 2.1.4.
but It was resolved by changing the keras version to 2.1.3.
Thank you!!
