### ISSUE TITLE
Error while training penn mpii multimodel 

### ISSUE THREAD

**Issue by imvinod** [dluvizon/deephar#55]
Hello,

Firstly, Thank you for your work. I found the paper very interesting and just the thing I was looking for. 

I want to train the model with my own dataset. But before that I tried to execute your training pipeline with `python3 exp/pennaction/train_penn_multimodel.py output/train-penn` 

I am getting this error after 1 epoch. 
`Traceback (most recent call last):
  File "exp/pennaction/train_penn_multimodel.py", line 160, in <module>
    trainer.train(30, steps_per_epoch=steps_per_epoch, initial_epoch=2,
  File "/home/ubuntu/3dexperiments/deephar/deephar/trainer.py", line 216, in train
    end_of_epoch_callback(epoch)
  File "exp/pennaction/train_penn_multimodel.py", line 127, in end_of_epoch_callback
    mpii_callback.on_epoch_end(epoch)
  File "/home/ubuntu/3dexperiments/deephar/exp/common/mpii_tools.py", line 156, in on_epoch_end
    scores = eval_singleperson_pckh(model, self.fval, self.pval,
  File "/home/ubuntu/3dexperiments/deephar/exp/common/mpii_tools.py", line 67, in eval_singleperson_pckh
    input_shape = model.get_input_shape_at(0)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/keras/engine/base_layer.py", line 2057, in get_input_shape_at
    return self._get_node_attribute_at_index(node_index, 'input_shapes',
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/keras/engine/base_layer.py", line 2683, in _get_node_attribute_at_index
    raise RuntimeError(f'The layer {self.name} has never been called '
RuntimeError: The layer Pose has never been called and thus has no defined {attr_name}.
Exception ignored in: <generator object OrderedEnqueuer.get at 0x7f71d0663ba0>
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/keras/utils/data_utils.py", line 780, in get
AttributeError: 'NoneType' object has no attribute 'Empty'
Exception ignored in: <generator object OrderedEnqueuer.get at 0x7f71d0663cf0>
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/keras/utils/data_utils.py", line 780, in get
AttributeError: 'NoneType' object has no attribute 'Empty'`

I spent quiet a bit of time figuring out but could not. I am not familiar with keras, unfortunately. I would really appreciate any pointers.
Thank you.

**Comment by dluvizon** [comment]
Hi @imvinod , sorry for the very late reply. The error comes from https://github.com/dluvizon/deephar/blob/fbebb148a3b7153f911b86e1a7300aa32c336f31/exp/common/mpii_tools.py#L67 from Keras. Have you checked the model at this point?
